### ISSUE TITLE
Empty, non-editable template,logic,output on AEM with different port than default 

### ISSUE THREAD

**Issue by andreibechet** [Adobe-Marketing-Cloud/aem-htl-repl#18]
I am running the AEM on a different port than the 4502, hence I have installed via the package manager. After the installation (which went without any issues) I cannot see anything under any of the files, nor can I edit. ![screen shot 2016-08-04 at 15 04 42](https://cloud.githubusercontent.com/assets/1832001/17402705/d9a7428c-5a54-11e6-9573-10744d45fcc8.png)

**Comment by asimarunava** [comment]
Press ctrl+u to see any exception is there or not.

like what i have been seeing like below

<h3>Full Exception:</h3>
<pre>
org.apache.sling.api.scripting.ScriptEvaluationException: org.apache.sling.scripting.sightly.SightlyException: Promise has completed with failure: Error: No resource found at path: /var/classes/sightly

**Comment by raducotescu** [comment]
This has been fixed with https://github.com/Adobe-Marketing-Cloud/aem-htl-repl/releases/tag/aem-htl-repl-1.0.4.
