### ISSUE TITLE
AEM Package has Hobbes dependency

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Marketing-Cloud/aem-htl-repl#21]
1.0.2 has a marked dependency on Hobbes package. I did not see how to obtain this dependency on the GH site (is this is a publicly available dependency?)

If its required the method for obtaining it should be clearly documented, if not it should be removed.

![image](https://cloud.githubusercontent.com/assets/1451868/18456715/1cb50a10-7908-11e6-8e72-dd54aa9abeaa.png)

**Comment by raducotescu** [comment]
Fixed with https://github.com/Adobe-Marketing-Cloud/aem-htl-repl/releases/tag/aem-htl-repl-1.0.4.
